name: Test Action

on:
  pull_request:
    branches: main
  push:
    branches: main
    tags:
      - '*'
  workflow_dispatch:

jobs:
  Keybase_Secret_Test:
    runs-on: [ubuntu-latest]
    steps:
      # Get the code
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get secrets from keybase
        id: secrets
        uses: ./
        with:
          action_command: keybase://public/bjgeiser/action_test/test.yaml
          action_type: secrets
          keybase_user: ${{ secrets.KEYBASE_USER }}
          keybase_paperkey: ${{ secrets.KEYBASE_PAPERKEY }}

      - name: Run get command (no path)
        uses: ./
        with:
          action_command: keybase://public/bjgeiser/action_test/test.yaml
          action_type: get
          keybase_user: ${{ secrets.KEYBASE_USER }}
          keybase_paperkey: ${{ secrets.KEYBASE_PAPERKEY }}


      - name: Run get command (output path)
        uses: ./
        with:
          action_command: keybase://public/bjgeiser/action_test/test.yaml get-test.yaml
          action_type: get
          keybase_user: ${{ secrets.KEYBASE_USER }}
          keybase_paperkey: ${{ secrets.KEYBASE_PAPERKEY }}

      - name: Run clone command
        uses: ./
        with:
          action_command: keybase://private/bjgeiser/action_test_repo
          action_type: clone
          keybase_user: ${{ secrets.KEYBASE_USER }}
          keybase_paperkey: ${{ secrets.KEYBASE_PAPERKEY }}

      - name: Run advanced clone command
        uses: ./
        with:
          action_command: -b main keybase://private/bjgeiser/action_test_repo repo_custom_folder
          action_type: clone
          keybase_user: ${{ secrets.KEYBASE_USER }}
          keybase_paperkey: ${{ secrets.KEYBASE_PAPERKEY }}

      - name: Keybase command test
        uses: ./
        with:
          action_command: fs cp keybase://public/bjgeiser/action_test/test.yaml keybase-test.yaml
          action_type: keybase
          keybase_user: ${{ secrets.KEYBASE_USER }}
          keybase_paperkey: ${{ secrets.KEYBASE_PAPERKEY }}

      - name: Raw command test
        uses: ./
        with:
          action_command: keybase fs cp keybase://public/bjgeiser/action_test/test.yaml raw-test.yaml
          action_type: raw
          keybase_user: ${{ secrets.KEYBASE_USER }}
          keybase_paperkey: ${{ secrets.KEYBASE_PAPERKEY }}

      - name: Batch command test
        uses: ./
        with:
          action_command: get keybase://public/bjgeiser/action_test/test.yaml batch1-test.yaml, get keybase://public/bjgeiser/action_test/test.yaml batch2-test.yaml
          action_type: batch
          keybase_user: ${{ secrets.KEYBASE_USER }}
          keybase_paperkey: ${{ secrets.KEYBASE_PAPERKEY }}

      - name: File command test
        uses: ./
        with:
          action_command: .github/workflows/test/test_commands.yaml
          action_type: file
          keybase_user: ${{ secrets.KEYBASE_USER }}
          keybase_paperkey: ${{ secrets.KEYBASE_PAPERKEY }}

      - name: Verifying Previous Steps
        shell: bash
        run: |
          echo "Echo out secrets from previous steps"
          echo "secret_name_1: ${{steps.secrets.outputs.secret_name_1}}"
          echo "secret_name_2: ${{steps.secrets.outputs.secret_name_2}}"
          echo "secret_name_3: ${{steps.secrets.outputs.secret_name_3}}"
          
          echo ""
          echo "test.yaml"
          cat test.yaml
          
          echo ""
          echo "get-test.yaml"
          cat get-test.yaml
          
          echo ""
          echo "keybase-test.yaml"
          cat keybase-test.yaml
          
          echo ""
          echo "raw-test.yaml"
          cat raw-test.yaml
          
          echo ""
          echo "batch1-test.yaml"
          cat batch1-test.yaml
          
          echo ""
          echo "batch2-test.yaml"
          cat batch2-test.yaml

          echo ""
          echo "file-test.yaml"
          cat file-test.yaml
          
          echo ""
          echo "file-test.json"
          cat file-test.json
          
          echo ""
          echo "Checking files on runner"
          ls -la .
          
          echo ""
          echo "> ls -la action_test_repo"
          ls -la action_test_repo
          
          echo ""
          echo "> ls -la repo_custom_folder"
          ls -la repo_custom_folder
          
